# Generated by Django 2.2.16 on 2022-02-11 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10, message='Оценка не может быть выше 10.'), django.core.validators.MinValueValidator(1, message='Оценка не может быть ниже 1.')]),
        ),
    ]
